### ISSUE TITLE
Parallel install with OpenSSL 1.0.2 and 1.1

### ISSUE THREAD

**Issue by dwmw2** [OpenSC/libp11#105]
Since OpenSSL 1.1 introduces a lot of API changes, it's likely to take applications a while to update. At least Fedora is planning to ship an openssl102 compat package in parallel with OpenSSL 1.1:
https://fedoraproject.org/wiki/Changes/OpenSSL110

This is fun because Fedora [packaging guidelines](https://fedoraproject.org/wiki/Packaging:SSLCertificateHandling) say that any package which accepts cert files should also accept RFC7512 PKCS#11 URIs by default, and we're filing bugs against any package that doesn't.

This means we need at least the engine to be built and installed in parallel for both OpenSSL 1.0.2 and 1.1. And maybe libp11 itself too.

To start with, it would be useful if libp11 actually used pkg-config to file the version of OpenSSL that it's building with. We don't seem to pick up the correct cflags/ldflags for OpenSSL at all, and fixing that would allow it to be built against a specific version of OpenSSL.

**Comment by nmav** [comment]
I'm not sure if we can have multiple libp11 packages installed as it is now. Most likely we need to introduce versioned symbols in libp11.

**Comment by dwmw2** [comment]
Just the engine would probably suffice for 1.0.2.

**Comment by mtrojnar** [comment]
Merged #129.

**Comment by nmav** [comment]
> Just the engine would probably suffice for 1.0.2.

That would require an engine that does link against a static libp11 rather than the shared one. What also of programs like openconnect which directly link to libp11? If linked against old openssl/libp11 combo and copied to a system where libp11 is linked with the new openssl they would most likely crash.

I think we need a soname in libp11 that matches the openssl one.
