### ISSUE TITLE
Call PKCS11_set_ui_method from engine interface

### ISSUE THREAD

**Issue by matthauck** [OpenSC/libp11#112]
(forked from discussion in PR #101)

The change in commit 7573c6e moved to using the `UI_METHOD*` specified on the PKCS11 key to grab the CKA_ALWAYS_AUTHENTICATE PIN rather than using the cached value. 

I think this will break keys loaded via the engine interface (`ENGINE_load_private_key`), since the caller will only receive an `EVP_PKEY` reference back and does not ever have a handle to the libp11 key object, and indeed an application need not link against libp11.dll at all and does not have access to the `PKCS11_set_ui_method`. 

So, it would seem to me that `eng_back.c` needs to call `PKCS11_set_ui_method` on the libp11 key object with whatever value is provided to `ENGINE_load_private_key` (and friends).

**Comment by mtrojnar** [comment]
Each `EVP_PKEY` object produced by libp11 either contains an RSA or an EC key.  They **do** have access to their corresponding `PKCS11_KEY` objects either via `rsa_ex_index` and `ec_ex_index`.

BTW: The engine now includes the contents of `libp11.dll`.  This is, however, totally irrelevant for this issue.

**Comment by matthauck** [comment]
Wait, what? Why close this?

Why put this burden on the application when it can be so easily done by
libp11? Sure, it's possible for the application to do, but can you explain
why should key reauths not automatically use the same UI as was used for
key load?

**Comment by mtrojnar** [comment]
`PKCS11_set_ui_method` is already executed on each `ENGINE_load_private_key`.

**Comment by matthauck** [comment]
Oh, hah. You're right, I totally missed it. :flushed:

**Comment by dwmw2** [comment]
So.... if two completely separate libraries within an application both use the same underlying hardware key (think different protocol plugins in an email or IM program or something) and they both have their own `EVP_PKEY` and both expect to deal with their own PIN callback... how does that work?

**Comment by mtrojnar** [comment]
@dwmw2  Good point.  It won't work.

The solution would be keep the UI pointers in RSA and EC ex_data instead of `PKCS11_KEY_private` objects.  This would be quite complex.  It is a pity OpenSSL doesn't have `EVP_PKEY_set_ex_data()`.  It would be useful for many features...

Do you think a real-life application is likely to bump into this problem?

**Comment by dwmw2** [comment]
> Do you think a real-life application is likely to bump into this problem?

Let's put it this way: It *intend* that it should. If a real-life application bumps into this problem, that's an indication that I'm succeeding with my **overall** goal with PKCS#11.

PKCS#11 should be as ubiquitous, for *nix systems, as the Windows certificate store and OSX Keychain are on those platforms. It should be *expected* that your key is in the store, not kept in some file somewhere. That way you can almost *automatically* get to take advantage of improved security, such as TPM or SGX/TrustZone to keep private key material *private*. I'm also going to be looking at virtual machine support... and it shouldn't *matter* if your whole web server VM was owned; the private key wasn't on it anyway because it was just accessed through the hypervisor.

So in that broader context... yes, absolutely. If you have two email accounts, or two IM accounts, set up using different keys or even the *same* key to authenticate, then I would certainly expect that key to be somewhere like in your GNOME keyring or a SoftHSM token even if you don't have actual hardware support.

In some cases (especially in NetworkManager) I'm actually fighting to *keep* file support alive. Now that PKCS#11 mostly Just Works, there is a repeated and forceful suggestion that we should just make people import their keys from files, then *only* use them from tokens. Wouldn't that be fun? :)

>  It is a pity OpenSSL doesn't have EVP_PKEY_set_ex_data(). It would be useful for many features...

It doesn't live there; put it in the `RSA` or the `EC_KEY` instead. The `EVP_PKEY` is just a very thin wrapper around those.

**Comment by dwmw2** [comment]
> It doesn't live there; put it in the `RSA` or the `EC_KEY` instead. The `EVP_PKEY` is just a very thin wrapper around those.

Hm, that does imply that we'd be creating a new `RSA` for each caller of `PKCS11_get_private_key()` instead of just handing out the same one repeatedly. That isn't our current model... but maybe it could work.

But in general, don't get too hung up on the `EVP_PKEY`. In fact, we should probably fix the `evp-sign.c` test case so that at the end of the `main()` function, *after* the call to `ENGINE_finish()`, it will call `EVP_PKEY_get1_RSA()` on the `private_key` and `public_key` variables on which it still holds a refcount, *then* `EVP_PKEY_free()`, then perform crypto operations using those `RSA` objects. And then *finally* free the RSA objects, and exit.

And we should run that test under `valgrind --leak-check=full` too, to make sure there are no leaks. It wants an `ENGINE_cleanup()` at least, I think, and that's even before the torture test I just suggested adding.

**Comment by mtrojnar** [comment]
Yes, you're right.  `PKCS11_KEY` only gets a single `EVP_PKEY` object.  Each library only gets a reference to the object, and not a private copy.  My solution just wouldn't work.
