### ISSUE TITLE
nginx service issue

### ISSUE THREAD

**Issue by atunc** [OpenSC/libp11#195]
Hello,

I have used nginx and HSM integration over last version of libp11. nginx has done ssl connection success with master_process off and daemon off parameters. But when i removed the these parameters from nginx.conf and start nginx service (**sudo nginx service start**), ssl connection is return error as below. 

Here is nginx error log

**2 SSL_do_handshake() failed (SSL: error:8207B0B3:PKCS#11 module:pkcs11_reload_key:Session handle invalid error:8207A0B3:PKCS#11 module:pkcs11_private_encrypt:Session handle invalid error:1409B006:SSL routines:SSL3_SEND_SERVER_KEY_EXCHANGE:EVP lib) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:443**

Could you help me please to resolve this error?
Thanks & Regards

**Comment by mtrojnar** [comment]
Can you be more specific?  What was the configuration that did work?  What were *these parameters* you have removed?

**Comment by atunc** [comment]
This error similar to [nginx hangs #156 issue](https://github.com/OpenSC/libp11/issues/156). I have added lines at below to  nginx config global section then nginx works with thales HSM over libp11. 

master_process off;
daemon off;

So, when i removed these parameters from nginx config, ssl connections getting error. Error line shows session is not valid for the forked process. Forked operations needs to reinitialize, I think pkcs11_CTX_reload function is not working clearly.

**Comment by mtrojnar** [comment]
It looks like an atfork issue.  Maybe @nmav, who authored this feature, will be able to help.

**Comment by mtrojnar** [comment]
@atunc Can you please check whether this issue is fixed in the current master?

**Comment by atunc** [comment]
thank you to fix its working with forking process now.

**Comment by egegorgun** [comment]
Hi,

We are also having the same issue with the following configuration:

```
Thales nCipher HSM with the latest firmware & software version
NGINX [1.16.1-0+bionic1]
OpenSSL [1.1.1d] (built NGINX with that)
OpenSC [0.19.0] (not sure about the active version, we had 0.17.0-3 through the official repo previously and we purged it, pkcs11-tool etc. is working, how can we be sure about the active version?)
p11-kit [0.23.9-2]
libp11-kit0 [0.23.9-2] (comes with p11-kit)
libp11 [0.4.10] (stand-alone version)
libssl-dev [1.1.1-1ubuntu2.1~18.04.4]
libssl1.1 [1.1.1-1ubuntu2.1~18.04.4]
libengine-pkcs11-openssl1.1 [0.4.7-1build1]
```

We are not able to set NGINX parameters master_process and daemon to off, otherwise NGINX doesn't start. With these in mind, sudo nginx -t reports:

```
Missing CKA_ALWAYS_AUTHENTICATE attribute
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

The output of our CURL request:

```
*   Trying 0.0.0.0...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: ./ca.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS alert, Server hello (2):
* error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
* stopped the pause stream!
* Closing connection 0
```

When we look at /var/log/nginx/error.log, the following is reported after 3 consecutive CURL requests:

```
2019/11/06 14:10:54 [crit] 15253#15253: *1 SSL_do_handshake() failed (SSL: error:820780E0:PKCS#11 module:pkcs11_open_session:No PKCS#11 token present error:141EC044:SSL routines:tls_construct_server_key_exchange:internal error) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:443
2019/11/06 14:11:47 [crit] 15253#15253: *2 SSL_do_handshake() failed (SSL: error:8207B0B3:PKCS#11 module:pkcs11_reload_key:Session handle invalid error:8207A0B3:PKCS#11 module:pkcs11_private_encrypt:Session handle invalid error:141EC044:SSL routines:tls_construct_server_key_exchange:internal error) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:443
2019/11/06 14:12:11 [crit] 15253#15253: *3 SSL_do_handshake() failed (SSL: error:8207A0B3:PKCS#11 module:pkcs11_private_encrypt:Session handle invalid error:141EC044:SSL routines:tls_construct_server_key_exchange:internal error) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:443
```
@atunc, what should we do to further dive into the issue as you faced it with the same device and scenario? Any help would be very much appreciated.

@mtrojnar do you have any suggestions? Thanks!

**Comment by dengert** [comment]
Use [OPenSC PKCS11 SPY](https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC)  or other trace of PKCS11 calls. 

May be unrelated, but looks like applications is looking for CKA_ALWAYS_AUTHENTICATE on private key but the PKCS11 module does not support the attribute.

**Comment by atunc** [comment]
@egegorgun The issue is same with forking process which is fixed in #206
you can check PKCS11 calls with enable debugs on nCipher module to dive into the issue.

**Comment by egegorgun** [comment]
Apologies for the delayed response. We have faced a problem with a fan of our HSM device and had to replace it to continue running our tests.

In the meantime, we set everything up from scratch and configured PKCS11 SPY and nCipher's debugger for tracing the calls.

@dengert, PKCS11 SPY reports the following:

`44: C_GetAttributeValue
2019-11-21 14:17:57.162
[in] hSession = 0x8cb
[in] hObject = 0x468
[in] pTemplate[1]: 
    CKA_ALWAYS_AUTHENTICATE  000056539669ae40 / 1
[out] pTemplate[1]: 
    CKA_ALWAYS_AUTHENTICATE  000056539669ae40 / 18446744073709551615
Returned:  18 CKR_ATTRIBUTE_TYPE_INVALID`

Similarly, nCipher's debugger reports the following:

`2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB <    rv 0x00000000 (CKR_OK)
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB >>   C_GetAttributeValue
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB >    hSession 0x000008CB
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB >    hObject 0x00000468
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 00000000 D    NFC__hash_session 0x000008CB
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB D    hashmap lookup hash 46569E98220 probe 32 step 5
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB D    lookup try hashmap[32] hash 46569E98220 value 0x565396698ee0
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB D    found hashmap[32] value 0x565396698ee0
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 00000000 D    NFC__hash_object_handle 0x00000468
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB D    hashmap lookup hash 2340A326979 probe 121 step 83
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB D    lookup try hashmap[121] hash 2340A326979 value 0x56539665f910
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB D    found hashmap[121] value 0x56539665f910
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB D    NFC__GetAttributeValuePrivKey, ckktype 0x00000000
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB D    NFC__check_attributes class 0x00000003 (CKO_PRIVATE_KEY) type 0x00000000 ulCount 1
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB Application error: Unknown attribute type 0x00000202
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB Warning: Some attributes invalid, continuing with more
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB D    Unknown attribute type (0x00000202) 0x00000202
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB D    Skipping invalid attribute
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB D    NFC__check_attributes class 0x00000003 (CKO_PRIVATE_KEY) type 0x00000000 ulCount 1
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB <    Unknown attribute type (0x00000202): Value not available
2019-11-21 14:17:57 [38393] t40f743a05e7f0000: pkcs11: 000008CB <    rv 0x00000012 (CKR_ATTRIBUTE_TYPE_INVALID)`

sudo nginx -t reports:

`2019/11/21 10:51:10 [crit] 33904#33904: *7 SSL_do_handshake() failed (SSL: error:8207A060:PKCS#11 module:pkcs11_private_encrypt:Key handle invalid error:141EC044:SSL routines:tls_construct_server_key_exchange:internal error) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:443`

Do you have any suggestions?

@ansasaki would you be kind enough to have a look at our issue as well?

**Comment by dengert** [comment]
Both the SPY and nCipher's debugger are saying the PKCS\#11 module does not support the attribute.

CKA_ALWAYS_AUTHENTICATE is defined in PKCS\#11 v2.20 "Table 30, Common Private Key Attributes" . It was introduced some time between V2.01 (1997) and 2.20 (2004) So it should not be considered invalid. If the PKCS\#11 module for the devices does not support it should return `CKA_FALSE`. 
The same goes for all  attributes defined in PKC\#11. 

`CKA_ALWAYS_AUTHENTICATE  000056539669ae40 / 1` is the  type of the attribute, address and length` 
`CKA_ALWAYS_AUTHENTICATE  000056539669ae40 / 18446744073709551615` is the type, address and looks uninitialized or invalid length (CK_LONG)  It should have printed  `CKA_ALWAYS_AUTHENTICATE  False` or `CKA_ALWAYS_AUTHENTICATE  / 1 False`

There are not many tokens that support `CKA_ALWAYS_AUTHENTICATE` (PIV was the first I know of that supportes in on the card) so the calling application could have made the assumption that a call to `C_GetAttributeValue`  for `CKA_ALWAYS_AUTHENTICATE` is assumed to be false if it does not succeed and continue on.

**Comment by egegorgun** [comment]
It appears that Thales/nShield/nCipher is still using PKCS#11 library version v2.01 (from 1997) on their latest module (which comes with Security World 12.60.3, from 2019) and that is why the CKA_ALWAYS_AUTHENTICATE attribute is regarded as invalid. As I understand, NGINX is making calls according to the v2.40 specification and nCipher's module is not able to interpret some attributes since they were not defined in v2.01 yet.

There are 5 major releases between v2.01 and v2.40 (current LTS version), which took 18 years, and yet, Thales, as a security company, has done nothing in 18 years to upgrade its PKCS#11 library support from v2.01 to the latest. Can you believe that?

**Comment by dengert** [comment]
I can believe it too. 

But in their defense, C_GetInfo will return major and minor and version numbers  So applications can take appropriate action.  I don't seeing OpenSC or libp11 checking versions. I doubt other applications do either. But it has been 15 years since 2.20 was released. 

The 18446744073709551615 in the SPY trace is  2^64 − 1 i.e. -1 as specified in PKCS#11 2.01 for invalid values for C_GetAttributeValue. 

So you could look at calling application. Is that really libp11? and add test for version > 2.20 before asking for CKA_ALWAYS_AUTHENTICATE. Or just treat an invalid response as false.

**Comment by mtrojnar** [comment]
> So you could look at calling application. Is that really libp11? and add test for version > 2.20 before asking for CKA_ALWAYS_AUTHENTICATE. Or just treat an invalid response as false.

This is how it's currently implemented:
https://github.com/OpenSC/libp11/blob/a41cbb29083545ceee8da35fa0067e402ed7d676/src/p11_key.c#L331-L337

**Comment by egegorgun** [comment]
It has been 7 months since I created a suppot ticket in December 2019 to ask Thales/nCipher release at least an hot fix to overcome this issue.

A couple of weeks ago, they informed me that they released an hot fix and today, I gave it a try. It seems like they have resolved the issue and their library now reports CKA_ALWAYS_AUTHENTICATE correctly.

However, we are now having a similar issue to [issue 206](https://github.com/OpenSC/libp11/pull/206) although we are using libp11 v0.4.10 and this should have been fixed already. When we configure NGINX config file (etc/nginx/nginx.conf) with the following, SSL connections get handled correctly:

master_process off;
daemon off;

When we remove these, forked operations do not get handled in the same session as the master process of NGINX and therefore don't see our preloaded softcard or key objects inside it. Do you have any suggestions?

**Comment by ojw-nc** [comment]
If you are preloading a softcard, then the preload file needs to be specified in the configuration/environment.
For example with:
`ppmk --preload --preload-file /opt/preload softcard1 pause`
Check your setup for the following:
`cat /etc/environment
export NFAST_NFKM_TOKENSFILE=/opt/preload
grep env /etc/nginx/nginx.conf
env NFAST_NFKM_TOKENSFILE=/opt/preload;
grep e_k /etc/nginx/nginx.conf
ssl_certificate_key "engine:pkcs11:pkcs11:token=softcard1;id=%01;pin-value=fake";`

**Comment by egegorgun** [comment]
@ojw-nc thank you for the information you have provided and apologies for the delayed response. I've been busy with a new project for the last couple of months and was tasked to work only on it.

NFAST_NFKM_TOKENSFILE environment variable was already globally available and pointing to our preload file, however, wasn't in the nginx.conf file. I added to there as well. However, it didn't help. I'm getting the following error:

`*1 SSL_do_handshake() failed (SSL: error:8207A060:PKCS#11 module:pkcs11_private_encrypt:Key handle invalid error:141EC044:SSL routines:tls_construct_server_key_exchange:internal error) while SSL handshaking, client: 172.31.88.4, server: 0.0.0.0:443`

Any suggestions?

**Comment by ojw-nc** [comment]
No worries; it seems from the error reported that something is not quite right still in the configuration/preload!
Rather than trying to debug it here, please can you log a support request with our team (where we can then share more details fully): https://www.ncipher.com/services/support/contact-support
I will be able to help with their investigation if/as required, and then we can perhaps share the resolution for future reference too...

**Comment by egegorgun** [comment]
@ojw-nc I actually have an interesting finding. While I was digging through (I checked the /proc/PROCESS_ID/environ file), I noticed that NGINX doesn't load any (global or from the configuration) environment variables (i.e. NFAST_NFKM_TOKENSFILE) if the following are removed:

master_process off;
daemon off;

Therefore, I assume, it doesn't detect the preload file. I event tried to set the environment variable through /lib/systemd/system/nginx.service, however, it seems that NGINX somehow automatically cleans its buffer for environment variables during service startup. What do you think?

By the way, I already have an open support request on nCipher Support portal with ID: 103640.

**Comment by ojw-nc** [comment]
I've tried it again on a new install just now and it works for me; you are correct that if it is being launched via systemd then you may need to include some appropriate directives there too.
In order to reproduce your setup, please can you confirm the platform and nginx version so I can validate on the same. If you are able to share the exact configuration too with our support team that would be much appreciated.

**Comment by egegorgun** [comment]
I've already shared all the details on the respective support ticket with nCipher's support team to move forward with the issue, but without success.

Yes, we are launching NGINX via systemd. Adding an Environment directive to NGINX's systemd file also didn't work out since NGINX disregarded it during service startup. 

Here’s what we are using:

- Thales nShield Connnect 6000+ HSM devices with the latest firmware
- Ubuntu v18.04 server distribution
- NGINX v1.16.1
- OpenSSL v1.1.1d
- OpenSC v0.20.0
- Libp11 v0.4.10
- p11-kit v0.23.21
- libengine-pkcs11-openssl v0.4.10-1 (OpenSSL engine for PKCS#11 modules)

@ojw-nc, thank you once again for your help. Would it be possible to exchange further information with you in private so that we won't bother everyone about everything until we come up with a solution? Thanks!

**Comment by ojw-nc** [comment]
Thanks for your reply. It is the "env" directive noted above that is responsible for setting the environment for the worker processes (http://nginx.org/en/docs/ngx_core_module.html#env). Perhaps you can double check that line is included, and the permissions are suitably set on the preload file too?
I've seen it work today on Ubuntu18.04 with both the included (1.14.0) and stated (1.16.1) NGINX versions - all other packages from the standard distribution.
If you are still having trouble: please can you build a new/clean environment from standard distribution packages somewhere we can login directly, and then reach out to our support team - I've asked them to pass your details on to me so we can talk directly if needed...

**Comment by egegorgun** [comment]
"By default, nginx removes all environment variables inherited from its parent process except the TZ variable."

It seems that when NGINX is run as a single and foreground process (not as a daemonized background process), it reads the env directive and therefore the preload file, and everything works as intended. However, when the following are removed from the configuration file (which is the way it should be done for a production environment), all previously set environment variables are removed:

master_process off;
daemon off;

Did you run your tests with the above parameters or without them?

**Comment by ojw-nc** [comment]
Running from systemd, you can see the parameters used (default on Ubuntu):
`ojw@ubuntu:~$ grep env /etc/nginx/nginx.conf
env NFAST_NFKM_TOKENSFILE=/opt/preload;
ojw@ubuntu:~$ sudo systemctl start nginx.service
ojw@ubuntu:~$ sudo systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-10-12 12:32:09 BST; 2s ago
     Docs: man:nginx(8)
  Process: 9837 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 9785 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
 Main PID: 9876 (nginx)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/nginx.service
           ├─9876 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─9879 nginx: worker process
           ├─9880 nginx: worker process
           └─9881 nginx: worker process

Oct 12 12:32:06 ubuntu systemd[1]: Starting A high performance web server and a reverse proxy server...
Oct 12 12:32:08 ubuntu nginx[9785]: Missing CKA_ALWAYS_AUTHENTICATE attribute
Oct 12 12:32:09 ubuntu nginx[9837]: Missing CKA_ALWAYS_AUTHENTICATE attribute
Oct 12 12:32:09 ubuntu systemd[1]: Started A high performance web server and a reverse proxy server.
`

**Comment by egegorgun** [comment]
NGINX is probably not reading the env directive you defined when you launch it with systemd and with parameters daemon on; master_process on; @ojw-nc. Did you have a look at the respective process' environ file (i.e. /proc/PROCESS_ID/environ)? Can you see "NFAST_NFKM_TOKENSFILE=/opt/preload" there?

I can launch NGINX without any errors as well but when it comes to offloading SSL connections, it throws an error since it doesn't read the env directive. Did you try to offload an SSL connection too? If not, can you kindly contact me through the support ticket so that we can organize a session to dive deep in the issue if possible? Thanks!

**Comment by ojw-nc** [comment]
The service may start regardless of the "env" directive being present - it is used by the worker processes for connection handling.

When such is used to set NFAST_NFKM_TOKENSFILE to the location used by the preload/ppmk command, I can straightforwardly show SSL connections being established (with for example, openssl s_client, curl or apachebench). If I remove or comment that directive then I get an error similar to yours shown above - so it is definitely having the desired effect on my test systems.

If you are still struggling, then definitely I would recommend to build a new/clean environment from standard distribution packages somewhere we can login directly for further troubleshooting.
