### ISSUE TITLE
Use pkcs11 by default (configuration file)

### ISSUE THREAD

**Issue by MatthiasLohr** [OpenSC/libp11#232]
Hello,

is it possible to configure the use of the pkcs11 engine via configuration file instead of command line? I want to get rid of ```-engine pkcs11 -keyfile "pkcs11:manufacturer=piv_II;id=%02" -keyform e```, that should be my default for every ```openssl ca``` operation.

Any hints?

Best regards and thanks in advance
Matthias

**Comment by dwmw2** [comment]
With OpenSSL 1.1 and the STORE facility we should be able to make this a lot easier. We should provide a STORE back end which supports PKCS#11 URIs, in parallel with the existing file loader.

**Comment by MatthiasLohr** [comment]
Sorry, no idea what you are talking about :smile:

Was that a ToDo item for me or for your project? Anyway... how can I help?

**Comment by dwmw2** [comment]
It's more a TODO item for the project or OpenSSL, but nothing prevents you from helping with either :)

OpenSSL has introduced a new '[STORE](https://github.com/openssl/openssl/blob/master/doc/man7/ossl_store.pod)' concept which takes URIs, which means it's easy enough to plug in the pkcs11: scheme handler alongside the existing file: handler. Anything using the new API _(as they should, because it makes opening keys+certs from files a lot easier than it [used to be](http://www.advogato.org/person/dwmw2/diary/205.html))_ will then Just Work™.

FWIW if you're using a distribution like Fedora, the packaging guidelines there state that applications SHOULD just accept a PKCS#11 URI on the command line in place of a filename, and do the right thing. I don't think '`openssl ca`' is going to catch up with that any time soon though :)

**Comment by mtrojnar** [comment]
As noted by @dwmw2 this feature request belongs to OpenSSL and not libp11.

**Comment by MatthiasLohr** [comment]
@mtrojnar, does libp11 support this STORE backend?

@dwmw2 mentioned
> We should provide a STORE back end which supports PKCS#11 URIs, in parallel with the existing file loader.

Sounds for me like a ToDo item for this project and as soon that is supporter by libp11 we could try to convince OpenSSL for doing that?

**Comment by mtrojnar** [comment]
I may reconsider adding support for the STORE backend **after** the support is added to OpenSSL.
