### ISSUE TITLE
Support for ed25519

### ISSUE THREAD

**Issue by 0x0ece** [OpenSC/libp11#287]
Any plan to support ed25519, similarly as done for EC in https://github.com/OpenSC/libp11/pull/260?

**Comment by mtrojnar** [comment]
Could you list the devices that support ed25519?  Can you show the the way ed25519 signing fails on those devices now?

**Comment by 0x0ece** [comment]
For example yubikey 5 today supports ed25519.

I was asking if it's already planned, because we're adding support for ed25519 signatures in our open source security key Solo (https://github.com/solokeys/solo) and this may inform how we implement it within our firmware.

Our final goal would be to support ssh authentication with ed25519 (via openssh + opensc pkcs11 driver), but there are "missing pieces" both in opensc and openssh agent, so we're trying to figure out who's already working on what and if there are guidelines or specs.

**Comment by mouse07410** [comment]
Please provide the reference confirming that Yubikey 5 supports Ed25519. 

I just checked Yubico web site, and for ECC it only listed P256 and P384 (as expected). Could you kindly explain which of the Yubikey applets (PIV, OpenPGP, U2F/WebAuthn, OTP) provides that support?

**Comment by 0x0ece** [comment]
Uh, you're right. I thought they added it to the 5, but it seems it's just in the HSM2:
https://developers.yubico.com/YubiHSM2/Product_Overview/

**Comment by mouse07410** [comment]
Yes, YubiHSM2 does offer Ed25519 support (EdDSA). They haven't added it to the FIPS-certified Yubikeys, mainly because neither the current PIV not OpenPGP standards define it's use. That's the reason why their PIV applet does not support RSA4096 (the hardware can do it, as OpenPGP applet demonstrates).

At this time I can live without EdDSA, as I see no great advantage it would provide (conspiracy theories aside).

**Comment by 0x0ece** [comment]
Got it, sounds good for now. We'll be back when things are more concrete. Thank you!

**Comment by Ryetschye** [comment]
> Got it, sounds good for now. We'll be back when things are more concrete. Thank you!

Hello dear OpenSC team,
I think from now on smartcard hardware do support Ed25519:
https://support.yubico.com/support/solutions/articles/15000027139-yubikey-5-2-3-enhancements-to-openpgp-3-4-support
It is possible to implement the Ed25519 support or is it still an unofficial feature?

**Comment by mtrojnar** [comment]
@Ryetschye I presume the current implementation doesn't work for you.  What is the error message?
Our EC implementation is not restricted to specific curves.  I think it should just work with Ed25519.

**Comment by Ryetschye** [comment]
I do not receive any error since I do not own any Yubikey 5. It was only a general question if it is worth to buy one. I require the Ed25519 signature feature but as long as OpenSC does not support it, I will use something like gpg to generate EdDSA signatures.

**Comment by mtrojnar** [comment]
Our libp11 project is not restricted to the OpenSC module.  As long as the vendor (Yubico) provides a PKCS#11 module, we should be able to support it.  Do you have a link to the vendor's PKCS#11 API documentation for this feature?

**Comment by mtrojnar** [comment]
@Ryetschye If your goal was to request Ed25519 in the OpenSC module, you should have crated an issue in https://github.com/OpenSC/OpenSC/ rather than https://github.com/OpenSC/libp11/.

**Comment by rvdgracht** [comment]
OPTEE supports  ED25519 since [this](https://github.com/OP-TEE/optee_os/commit/03e07432b68f9d78dbad4b9a8af50705948e7893) commit.

I'm running the PKCS11 TA in optee 0.21.0. I can generate a keypair with pkcs11-tool using the libckteec.so.0
module from the optee-client package (same version).

I used [optee userland_integration](https://optee.readthedocs.io/en/stable/building/userland_integration.html#pkcs-11-driver) as a guide.

If I change KEY_TYPE to 'rsa:2048' the following does work as expected. Since the key is 'not found' I suspected this might be an issue with libp11. It is listed when I'm using `pkcs11-tool -O -l`.

# My optee-pkcs11.conf:
openssl_conf = openssl_init

[openssl_init]
engines = engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
dynamic_path = /usr/lib/engines-3/libpkcs11.so
MODULE_PATH = /usr/lib/libckteec.so.0
init = 0
 
[req]
distinguished_name = req_distinguished_name
 
[req_distinguished_name]

# My environment:
`TOKEN=optee-ta`
`SO_PIN=1234123412341234`
`PIN=00000000`
`KEY_LABEL=mykey`
`KEY_URI="pkcs11:token=$TOKEN;object=$KEY_LABEL;type=private;pin-value=$PIN"`
`KEY_TYPE=EC:edwards25519`

# My steps:
`pkcs11-tool --init-token --label $TOKEN --so-pin $SO_PIN`
`pkcs11-tool --label $TOKEN --login --so-pin $SO_PIN --init-pin --pin $PIN`                                       
`pkcs11-tool -l --keypairgen --key-type="$KEY_TYPE" --label $KEY_LABEL --id 0 --pin $PIN`
`OPENSSL_CONF=optee-pkcs11.conf openssl req -new -engine pkcs11 -keyform engine -key "$KEY_URI" -subj "/CN=MY CSR" -out csr.pem`

The last command fails with:
Engine "pkcs11" set.
Unable to enumerate private keys
The private key was not found at: pkcs11:token=optee-ta;object=mykey;type=private;pin-value=00000000
PKCS11_get_private_key returned NULL
Could not read private key from org.openssl.engine:pkcs11:pkcs11:token=optee-ta;object=mykey;type=private;pin-value=00000000
2050FA76:error:40000065:pkcs11 engine:ERR_ENG_error:object not found:eng_back.c:887:
2050FA76:error:13000080:engine routines:ENGINE_load_private_key:failed loading private key:crypto/engine/eng_pkey.c:79:

# relevant package versions
openssl - 3.1.1
optee-client - 3.21.0
libp11 - 0.4.12

**Comment by mtrojnar** [comment]
> libp11 - 0.4.12

Have you tried testing this against the current master branch?

**Comment by rvdgracht** [comment]
I just did with the same results

**Comment by rvdgracht** [comment]
I did some digging and found that the key type (CKK_EC_EDWARDS / 0x40) is not handled in
[src/p11_key.c#L96](https://github.com/OpenSC/libp11/blob/master/src/p11_key.c#L96) causing the error I'm seeing.

**Comment by big-dog22** [comment]
Is there any update on this?  I'm using YubiHSM 2 and we want the ed25519 algorithm.  I have a call like this:

pkcs11-tool --module "C:\Program Files\Yubico\YubiHSM Shell\bin\pkcs11\yubihsm_pkcs11.dll" --login --pin xxxxxxxx --keypairgen --key-type **ed25519** --label "Root CA" --usage-sign
Using slot 0 with a present token (0x0)
**error: Unknown key pair type ed25519**
Aborting.

**Comment by joanandk** [comment]
Hi,
Me too is in need for the support for newer Yubikey (5.7) and ED25519 (not ed25519-sk) via PIV.

Thanks and BR

**Comment by dengert** [comment]
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-78-5.pdf July 2024 table 9 does not list any ED curves, only  3 RSA keys sizes and 2 EC curves. 

So if Yubico has added ED2519 to its PIV like applet it is not standard PIV.  

They do support ED curves in OpenPGP applet using the IETF experimental RFCs. But not the IETF standard track RFCs.    

Although these do not address libp11directly, they may if you are using OpenSC.  
Also look at https://github.com/OpenSC/OpenSC/pull/3090,  https://github.com/OpenSC/OpenSC/issues/2952 and https://github.com/OpenSC/OpenSC/issues/3000
which address PKCS11 curveNames and handling of Edwards and Montgomery curves and creation on OpenPGP cards.

**Comment by joanandk** [comment]
@dengert Thanks for your reply and sorry for the scarce information from my side. My workflow is the following: Yubikey (fw 5.7 and higher) supports ED25519 keys in the PIV slot 9a. The private key is loaded into the key and a certificate is generated which has the public key and is imported to the slot 9a.
As the format for the private key is PEM, I made use of openSSL to generate the private key and the yubico-piv-tool to generate the corresponding public key. This seems to be set up correctly, as the certificate states that the key is ED25519.
If I now try to load the keys via "_ssh-keygen -D /usr/lib64/opensc-pkcs11 -e_", I get "_skipping unsupported key type_".
So, as I do not use the Yubikey to generate my key pairs, I think this should work, what does not. If I interpret the error message, I conclude that ED25519 via PIV is not supported.

BR

**Comment by dengert** [comment]
@ghost  your issue is with OpenSC pkcs11 and keygen.

OpenSC support for generating keys via pkcs11 needs improvement and not all OpenSC card drivers (PIV does not) support this and is complicated by  OpenPGP use of early IETF experimental RFC terminology which has now been changed in IETF standard track RFCs and PKCS11 V3 standards.

@joanandk  your are using OpenSC with "ssh-keygen -D /usr/lib64/opensc-pkcs11 -e".  So this issue is not directly a libp11 issue, but an OpenSC issue. 

I would suggest that your open an issue in https://github.com/OpenSC/OpenSC/issues  In the mean time try and use the Yubico pkcs11 module. https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html

OpenSC's ability to use a Yubikey PIV with ED25119 key and cert already loaded may be a simple change.

**Comment by joanandk** [comment]
"_In the mean time try and use the Yubico pkcs11 module._"
I have already tried it. There were no modifications in the pkcs module of Yubico since 2020 and only supports up to RSA 3072. I have asked Yubico and am awaiting their resonse or roadmap when Yubico pkcs11 will support ED25519. If I do not hear anything from Yubico within a week, I will open an issue at OpenSC.

Thanks for you help

BR

**Comment by joanandk** [comment]
@dengert I am in contact with Yubico and have send them steps to reproduce my issue. If you want, I can tell you what the outcome is.
_yet for ED_ I have seen that too, but as I haven't fully understood the interaction of openSC, openSSL and openSSH, it is good to know that you doubt that there is a chance that YKCS11 hasn't implemented ED curves yet.

BR

**Comment by dengert** [comment]
I have ordered a token with 5.7.x and will generate a ED25519 key on it using their `yubico-piv-tool` and have started looking OpenSC `card-piv.c`, `pkcs15-piv.c` and `piv-tool.c` to support using the key from OpenSC PKCS11 module. Looks straight forward.

**Comment by matthewlegitt** [comment]
@dengert 

> I have ordered a token with 5.7.x and will generate a ED25519 key on it using their `yubico-piv-tool` and have started looking OpenSC `card-piv.c`, `pkcs15-piv.c` and `piv-tool.c` to support using the key from OpenSC PKCS11 module. Looks straight forward.

I'm Matthew, I'm the Principal Support Engineer with Yubico, if you don't mind opening a support case[ here](https://support.yubico.com/hc/en-us/requests/new) and reference this comment, we can get you some keys for testing.

**Comment by dengert** [comment]
@matthewlegitt 
OK, opened a Yubico request at  https://support.yubico.com/hc/en-us/requests/new

As noted this is also about: https://github.com/OpenSC/OpenSC/issues/2952

**Comment by SecT0uch** [comment]
@dengert Is this commit: https://github.com/OpenSC/OpenSC/pull/3090 the one that would allow ED25519 via PIV  with Yubikey (5.7) ?

I'm trying to understand if I have an issue or if it hasn't been implemented yet.

Like @joanandk, I genereated the key and certificate and this is what I get:
```
$ ykman piv info
PIV version:              5.7.1
PIN tries remaining:      3/3
PUK tries remaining:      3/3
Management key algorithm: AES256
Management key is stored on the YubiKey, protected by PIN.
CHUID: <REDACTED>
CCC:   No data available
Slot 9A (AUTHENTICATION):
  Private key type: ED25519
  Public key type:  ED25519
  Subject DN:       CN=Yubikey SSH
  Issuer DN:        CN=Yubikey SSH
  Serial:           <REDACTED>
  Fingerprint:      <REDACTED>
  Not before:       2025-01-03T13:29:42+00:00
  Not after:        2124-12-10T13:29:42+00:00

$ ssh-keygen -D /usr/lib/opensc-pkcs11.so
skipping unsupported key type
failed to fetch key
unknown certificate key type
failed to fetch key
Enter PIN for 'Yubikey SSH':
skipping unsupported key type
failed to fetch key
unknown certificate key type
failed to fetch key
cannot read public key from pkcs11

$ ssh-keygen -D /usr/lib/libykcs11.so
skipping unsupported key type
failed to fetch key
unknown certificate key type
failed to fetch key
unknown certificate key type
failed to fetch key
ssh-rsa <REDACTED> Public key for PIV Attestation
```

Similarly I'm unable to use it with `ssh -I` or `ssh-add -s`.

**Comment by dengert** [comment]
3090 is still a PR. /usr/opensc-pkcs11.so would not have the changes yet.
