### ISSUE TITLE
only first certificate is returned

### ISSUE THREAD

**Issue by gfrankliu** [OpenSC/libp11#297]
I was testing @nmav patch http://mailman.nginx.org/pipermail/nginx-devel/2015-July/007126.html to load certificate from HSM using softhsm. I stored the chain but it seems only the first cert in the chain is returned. Does pkcs11 not support the chained cert?

**Comment by mtrojnar** [comment]
PKCS#11 indeed does not support certificate chains.

**Comment by dwmw2** [comment]
That isn't strictly true. It's perfectly feasible to build up a chain by looking up each cert's issuer from PKCS#11, one at a time. OpenConnect does it, to ensure that it presents as full a chain as possible to the server.

http://git.infradead.org/users/dwmw2/openconnect.git/blob/HEAD:/gnutls.c#l1597

**Comment by mtrojnar** [comment]
@dwmw2 I beg to differ.  I did **not** write that is infeasible to implement certificate chains on top of PKCS#11.  I only wrote that **PKCS#11** does not support certificate chains.  It is still possible to implement the functionality on top any flat object storage, such as a directory with a bunch of DER files, or PKCS#11 in this case.  So yes, you may still download all the certificate objects and build a chain the same way you may do it with a directory of individual DER files, although neither PKCS#11 nor filesystems have any built-in support for this functionality.

**Comment by dwmw2** [comment]
You don't have to download all the certificate objects; given one certificate, you can look up its issuer directly.

Saying "PKCS#11 does not support certificate chains" might be taken to imply that it's impossible to get this right, if you're using PKCS#11, and that the user should not bother asking. That inference would be incorrect.

**Comment by mtrojnar** [comment]
Which PKCS#11 function would you use to lookup the certificate?

**Comment by dwmw2** [comment]
`C_FindObjects()`

**Comment by dwmw2** [comment]
The example I gave was using `gnutls_pkcs11_get_raw_issuer()`. You could see how that is implemented in the GnuTLS source code.

**Comment by mtrojnar** [comment]
@dwmw2 You are right and I was wrong.  It is indeed possible to lookup certificates stored in PKCS#11 by their DN.  I found the gnutls function that implements it: https://lgtm.com/projects/gl/gnutls/gnutls/latest/files/lib/pkcs11.c#x7285761973f11de7:1

**Comment by dwmw2** [comment]
Thanks. I confess I didn't actually *do* this for myself; I just used the functionality that GnuTLS provides, thanks to @nmav. In OpenConnect I do use libp11 directly instead of just using the ENGINE, precisely so that I can provide a better user experience — but that doesn't seem to include finding the issuers out of PKCS#11 as I should. So certain use cases will only work in the GnuTLS build.

For the general case, I'd really like things to Just Work for applications without them having to jump through hoops. OpenSSL should make it hard to get this kind of thing *wrong*, instead of making it hard to get it right. Perhaps the new `OSSL_STORE` functionality will make this possible, with the SSL code finding issuers in the store on demand?
