### ISSUE TITLE
Implement PKCS11_CTX_reload

### ISSUE THREAD

**Issue by stalowyjez** [OpenSC/libp11#361]
It seems that PKCS11_CTX_reload is on the public API, but it is not implemented - I think it would be reasonable to either implement it (pkcs11_CTX_reload is ready, so it would be just another 5 line function in p11_front.c) or remove it from the header.

**Comment by mtrojnar** [comment]
@nmav In https://github.com/OpenSC/libp11/commit/ecb83dad73ae39afb24b3cea294d44b7f3e3a6f1#diff-7538fe2ca1e59b3a6093e8d95e298110R143 you added `PKCS11_CTX_reload` to the public header, but this function, but it was never really exported the library https://github.com/OpenSC/libp11/blob/master/src/libp11.exports.  Since nobody complained about it for the last 5 years, I guess it is safe to remove it from the public header.  Am I right?

**Comment by nmav** [comment]
If it was never exported, I guess it is.
