### ISSUE TITLE
Any plans for an openssl provider?

### ISSUE THREAD

**Issue by jschmidb** [OpenSC/libp11#432]
Hello, I'm an employee of IBM Germany and I have used the libp11 engine a couple of years ago in a proof-of-concept involving Apache and HSMs. As with openssl 3.0 engines are more or less deprecated and the new concept are "providers", I wonder if you will transform the libp11 engine into a provider? Can you share any info on this?
Kind regards, Joerg

**Comment by williamcroberts** [comment]
Theirs also issue in pkcs11 libraries that are updated to openssl 3. If an engine is loaded, their's no way I have found through non-deprecated APIs, to load a public key and use it in rsa encryption. Under the hood it will end up tethering the ENGINE to the EVP_KEY_CTX instead of a provider capable of using the newer APIs.

We really need to get a plan to update this to the provider interface.

**Comment by enaess** [comment]
@mtrojnar - I was trolling through the OpenSSL site looking for the plans or a PKCS#11 interface, but couldn't find any. Do you have a reference or link?

**Comment by gilweis** [comment]
Is there any new information regarding the possibility of using pkcs11 as a provider?

**Comment by dengert** [comment]
> Is there any new information regarding the possibility of using pkcs11 as a provider?

https://github.com/simo5/libp11/tree/ossl3provider looks interesting. But it is not clear how this will replace the parts of libp11 engine that deal with loading certificates once OpenSSL drops engines. 

> AFAIK OpenSSL had a plan to develop their own PKCS#11 provider. 
Has anyone heard anything on this?

**Comment by mtrojnar** [comment]
> > Is there any new information regarding the possibility of using pkcs11 as a provider?
> 
> https://github.com/simo5/libp11/tree/ossl3provider looks interesting.

I hope @simo5 submits a PR when he decides that his code is mature enough.

> But it is not clear how this will replace the parts of libp11 engine that deal with loading certificates once OpenSSL drops engines.

Do you mean they'll drop the public API for constructing EVP_PKEY objects?  I'm not sure whether it's only useful for engines and whether OpenSSL considers it as a part of the ENGINE interface.  But, sadly, it's also marked as deprecated.

I doubt they intend to drop EVP_PKEY entirely.

> > AFAIK OpenSSL had a plan to develop their own PKCS#11 provider.
> > Has anyone heard anything on this?

I don't remember where I heard about it.  I vaguely remember seeing it on a mailing list years ago.

BTW: There is also at least one other unrelated project implementing a PKCS#11 provider: https://github.com/latchset/pkcs11-provider/

**Comment by dengert** [comment]
My concern was many of the OpenSSL apps allow for the use of engine for specific keys or certs. It is not clear how they will convert these to using a provider.  for example `openssl pkeyutl -help` has `-peerform PEM|DER|ENGINE`, `-keyform PEM|DER|ENGINE`,  `-engine val` and `-engine_impl`  During any conversions, they would have to support both engines and providers or just switch to provider only. It might be possible to distinguish an engine for a provider so the user interface would not have to change.  In OpenSSL source:  `grep "load_key("  openssl/apps/*`  note the user of  engine in many of the apps. 

> I do not think libp11 can be converted to a provider without a full rewrite which is why I started pkcs11-provider instead.

@simo5 Can you explain why libp11 can not be converted to a provider? 

Is the problem providers don't have the flexibility to be used for selected keys like the apps do with engines?

**Comment by simo5** [comment]
@dengert providers are much more complex, as I changed more and more code I ended up finding that I was using basically none of the libp11 code, and trying to use it was causing more work than not using it as the abstractions in libp11 do not match well with the providers interface.

For example the internal use of deprecated RSA or EC key structures internally was a problem, because providers only use pkeys, so it was forcing me to do multiple conversions as well as getting deprecation errors in compiling.

In the end it was much simpler to create a whole new body of work.

As for keys, the good thing about providers is that you can tell openssl which to use.
In the pkcs11-provider case I have a URI encoding backend, so if you reference keys by the pkcs11: URI then the pkcs11 provider is always used by default (assuming you loaded it via openssl.cnf). if you use PEM files instead the openssl "default" provider is used.

For example this automatically extracts a public key from a pkcs11 token using the pkcs11-provider (which needs to be configured in openssl.cnf):
openssl pkey -in "pkcs11:id=%0d%e1%e6%f9%fb%3f%c6%4f%50%b9%ca%2f%fa%3a%c3%2c%f4%49%d7%a2"  -pubin -pubout -out testcert.pem

(keys can also be referenced via labels and other filters, not just ids)

I have not experimented trying to use PEM files with the pkcs11 provider, mostly because I do not see the point of doing that, if the keys are in PEM files openssl can already use them directly.

**Comment by dengert** [comment]
libp11 package consists of  the libp11 and an engine that uses libp11. At one time they were different packages.  
So if you take the approach of writing a provider that does not use libp11 that solve the problem of OpenSSL deprecating engines.  

> For example the internal use of deprecated RSA or EC key structures internally was a problem, because providers only use pkeys, so it was forcing me to do multiple conversions as well as getting deprecation errors in compiling.

But for those who use libp11 the deprecation of internal RSA and EC key structures still needs to be fixed by using EV_PKEY.  The current libp11 has old code from when OpenSSL had ECDSA_METHOD and  ECDSA_METHOD which in OpenSSL 1.1 were combined into EC_KEY_METHOD. It looks like now is the time to replace RSA_METHOD,  ECDSA_METHOD and  ECDSA_METHOD with EV_PKEY, and use OPenSSL-1.1.1 and OpenSSL-3.0.X without using deprecated functions.  

> For example this automatically extracts a public key from a pkcs11 token using the pkcs11-provider (which needs to be configured in openssl.cnf)

It looks like you and OpenSSL have addressed my concern of keeping the user interface the same when using an pkcs11 engine or pkcs11 provider. 

If the libp11 is split into two packages again, i.e. your pkcs11-provider and a libp11 built without an engine when using OpenSSL-3 (no deprecated)  that could  still work.  Or we could fix libp11 to use EVP_PKEY and go back to using your ossl3provider. 

I hope to try building your pkcs11-provider in the near future.

**Comment by enaess** [comment]
I am following this conversation with keen interest. The pppd daemon has some provisions for using libp11 and it's abstraction and is looking forward to the next steps, e.g. use pkcs11-provider with openssl 3.0.0, or whatever else openssl 3.0.0 comes up with. 

@simo5 how compatible is the pkcs11-provider in terms of use, does it permit the same / similar pkcs11 urls by RFC that the libp11 interface uses, it's just a different setup to drop in the right library (that is, how much of the code in pppd need to change to support this)? Also, does the pkcs11-provider support SoftHSM module(s), basically a software layer for you to test the smart-cards without necessarily going out and buying one?

**Comment by enaess** [comment]
I don't care as much to which software emulator I use for testing the Smart Card integration, if SoftHSM is out or replaced with a different one, that is cool.

From my view, any documentation on how to set up this with popular smart cards from Yubico, or just a software based one would be very helpful. You have a reference to the PR you mentioned?

Sounds like updating the openssl.cnf to use the pkcs11 provider as an engine, change the pppd to use the engine API and then specify the correct pkey:urls for keys and certificates, it should be a workable solution. Did I understand that right?

**Comment by simo5** [comment]
There is no more special engines api to use.
You use the normal load/store API from openssl 3.0 to load keys using URIs.

The code can be fully transparent to whether you are using a provider or a normal pem file with openssl default provider, with the only difference being whether you are passing in /path/to/pem/file vs pkcs11:id=someid at runtime.

Of course the pkcs11: uri will work only if openssl has the pkcs11 provider loaded, but you can make the application completely oblivious to it if you use the right APIs, so you do not need special casing in the application itself.

Here you can see how to currenlty use a NSS softoken: https://github.com/latchset/pkcs11-provider/blob/main/tests/test.sh

**Comment by enaess** [comment]
Thank you so much. I'll have a look to see if I am able to configure this with pppd some time soon.

**Comment by dengert** [comment]
There is a catch-22 after a key is generated and attempting to create a CSR. Depending on the type of card, the public key may only be accessible at the time the key is generated. A CSR  contains the public key and is signed by the private key. So in some situations the public key is stored off the card to be used to ad it to the CSR. 

See:
https://github.com/latchset/pkcs11-provider/discussions/83#discussioncomment-4060357
and
https://github.com/openssl/openssl/blob/master/crypto/x509/x_pubkey.c#L364

**Comment by dengert** [comment]
In regards to the catch-22 situation of public key being lost, YKCS11 takes card of this:

https://developers.yubico.com/yubico-piv-tool/YKCS11/
> Key Generation
Key pair generation is a particular operation, in the sense that within PIV this is the only moment where the newly created public key is given back to the user. To prevent the key from being lost, it is automatically stored within the YubiKey by wrapping it in an X.509 certificate.
