### ISSUE TITLE
Softhsm2 blames pcks11.so for heap corruption segfault

### ISSUE THREAD

**Issue by hcoin** [OpenSC/libp11#526]
https://github.com/opendnssec/SoftHSMv2/issues/738

**Comment by olszomal** [comment]
I think that this issue is specific to certain OpenSSL versions that cause a segmentation fault during private key operations.
The fault occurs in engine operations and has been addressed upstream with commit https://github.com/openssl/openssl/commit/39ea783.
This was resolved with the workaround in PR https://github.com/OpenSC/libp11/pull/554

I suggest closing this issue.
