### ISSUE TITLE
OpenSSL Load pkcs11 error

### ISSUE THREAD

**Issue by PIKACHUIM** [OpenSC/libp11#542]
OpenSSL 3.0.14 LTS ZIP File (x64/x86) 
https://download.firedaemon.com/FireDaemon-OpenSSL/openssl-3.0.14.zip

.\WinSSL\bin\openssl.exe engine dynamic -pre SO_PATH:".\libp11\32bit\pkcs11.dll" -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:".\pkcs11\opensc-pkcs11.dll"
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:.\libp11\32bit\pkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Failure]: LOAD
BCAD0000:error:12800067:DSO support routines:win32_load:could not load the shared library:..\crypto\dso\dso_win32.c:108:filename(.\libp11\32bit\pkcs11.dll)
BCAD0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:..\crypto\dso\dso_lib.c:152:
BCAD0000:error:13000084:engine routines:dynamic_load:dso not found:..\crypto\engine\eng_dyn.c:442:
[Failure]: MODULE_PATH:.\pkcs11\opensc-pkcs11.dll
BCAD0000:error:13000089:engine routines:int_ctrl_helper:invalid cmd name:..\crypto\engine\eng_ctrl.c:90:
BCAD0000:error:13000089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:..\crypto\engine\eng_ctrl.c:258:

**Comment by olszomal** [comment]
It looks like the path ".\libp11\32bit\pkcs11.dll" to the PKCS#11 engine may be incorrect.
Use the dumpbin tool (if you have Visual Studio) with the following command:
```
dumpbin /exports .\libp11\32bit\pkcs11.dll
```
This command will display all symbols exported by the library. Look for the symbols `bind_engine` and `v_check`.

You also need to check the compatibility between the OpenSSL version and the PKCS#11 engine. The output below shows that the installed OpenSSL version is 3.3.2, and `dumpbin` indicates that `pkcs11.dll` is linked against `libcrypto-3-x64.dll`:
```
openssl version
OpenSSL 3.3.2 3 Sep 2024 (Library: OpenSSL 3.3.2 3 Sep 2024)

dumpbin /imports "C:\Users\M\Downloads\libp11-0.4.13_git-x64\pkcs11.dll" | findstr libcrypto
    libcrypto-3-x64.dll
```

Note that the `MODULE_PATH` argument is set with `-post` instead of a `-pre`.

```
openssl.exe engine dynamic -pre SO_PATH:"C:\Users\M\Downloads\libp11-0.4.13_git-x64\pkcs11.dll" -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -post MODULE_PATH:"C:\Users\M\Downloads\libp11-0.4.13_git-x64\libp11.dll" -t
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:C:\Users\M\Downloads\libp11-0.4.13_git-x64\pkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Success]: LOAD
Loaded: (pkcs11) pkcs11 engine
     [ available ]
[Success]: MODULE_PATH:C:\Users\M\Downloads\libp11-0.4.13_git-x64\libp11.dll
```

I recommend closing this issue.
