### ISSUE TITLE
Compiling on Windows with Msys2

### ISSUE THREAD

**Issue by yasinkahramaner** [OpenSC/libp11#84]
Hi there,

I downloaded libp11-0.4.0. I used MSYS2 environment to configure and make the project.

It works very well with ./configure

Yet when I execute make, I receive the following error:

`libtool: link: warning: undefined symbols not allowed in i686-pc-mingw32 shared libraries
  CCLD     pkcs11.la

*** Warning: This system can not link to static lib archive libp11.la.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have.
*** But as you try to build a module library, libtool will still create
*** a static module, that should work as long as the dlopening application
*** is linked with the -dlopen flag to resolve symbols at runtime.
libtool: link: warning: undefined symbols not allowed in i686-pc-mingw32 shared libraries
cd .libs && cp -pR -f pkcs11.dll libpkcs11.dll
cp: cannot stat ‘pkcs11.dll’: No such file or directory
Makefile:981: recipe for target 'all-local' failed
make[2]: *** [all-local] Error 1
make[2]: Leaving directory '/c/libp11-0.4.0/src'
Makefile:405: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/c/libp11-0.4.0/src'
Makefile:465: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

We will appreciate for any help.

**Comment by mtrojnar** [comment]
MSYS2 is indeed not supported.  I would gladly merge a pull request correcting this issue.

**Comment by nased0** [comment]
Hello
I  made current libp11-master version, that has autoconf and automake patches necessary for mingw, but it is not possible to compile included examples, because mingw does not support termios.h, so my patches may hurt linux builds. You can probably correct it using if !win32 condition, that I used to prevent error shown in previous post. In src\Makefile.am
install-exec-hook:
if !WIN32
	cd '$(DESTDIR)$(enginesdir)' && $(LN_S) -f pkcs11$(SHARED_EXT) libpkcs11$(SHARED_EXT)
endif
But I think that it should be done by someone that knows autoconf better than me.
My version has my "unhack" enabled to allow it to function correctly with curl and openssl s_client. 
https://github.com/OpenSC/libp11/issues/122#issuecomment-253213951
atfork.c was modified like this:
#ifdef __WIN32__
# include <winsock2.h>
#else
# include <sys/socket.h>
#endif

Anyway, you have libp11.dll and pkcs11.dll conveniently compiled in src\.libs
It works fine with my libcurl based app and it is all I care about.
[libp11-master.zip](https://github.com/OpenSC/libp11/files/532048/libp11-master.zip)

**Comment by nased0** [comment]
IMO the best solution would be to fix examples to be mingw friendly - without terminal I/O interface.

**Comment by mtrojnar** [comment]
I agree.  Please submit a pull request.

**Comment by nased0** [comment]
Submitted
https://github.com/OpenSC/libp11/pull/125

IMO the correct solution to this bug is to copy pkcs11.dll to the engine folder before creating the symbolic link:
```
install-exec-hook:
	cp -pR -f .libs/pkcs11$(SHARED_EXT) $(DESTDIR)$(enginesdir)/pkcs11$(SHARED_EXT) \
 	&&  cd '$(DESTDIR)$(enginesdir)' && $(LN_S) -f pkcs11$(SHARED_EXT) libpkcs11$(SHARED_EXT)
```

**Comment by mtrojnar** [comment]
#125 was merged.
