### ISSUE TITLE
INIT_ARGS engine control command is broken

### ISSUE THREAD

**Issue by matthauck** [OpenSC/libp11#91]
I am trying to initialize my HSM with threading support enabled, but see no way to do that with the current pkcs11 engine interface. If `INIT_ARGS` command is not specified at all and is left NULL, then [pkcs11_CTX_load](https://github.com/OpenSC/libp11/blob/1e249dc/src/p11_load.c#L83) calls `C_Initialize` with NULL. However, if I specify a non-null value for `INIT_ARGS`, then it assigns that value to `pReserved`, which the [PKCS11 spec specifies](https://www.cryptsoft.com/pkcs11doc/v220/pkcs11__all_8h.html#aCK_C_INITIALIZE_ARGS) should always be `NULL_PTR` and thus returns with an error. 

pkcs11 engine needs a way to set a flag that says "specify empty init args" without needing to set an invalid `pReserved` value. The reason for needing this is that some libraries (e.g. SoftHSMv2) requires that a non-NULL CK_C_INITIALIZE_ARGS value be passed to enable multi-threading.

**Comment by mtrojnar** [comment]
You are absolutely right. The bug is caused by the ugly workaround introduced in https://github.com/OpenSC/libp11/commit/9c837e4b1eb5eaf9b9c4a373ff5f9de1dfc4d63d, which passes the `args` structure conditionally, instead of setting the `CKF_OS_LOCKING_OK` flag (added later in https://github.com/OpenSC/libp11/commit/0ab1b61967f10ccdfbfc250f7fe1e7cdfaf311da).

My long-term plan for this is to replace OS locking with OpenSSL dynamic locks.  In the meantime, I'll just revert https://github.com/OpenSC/libp11/commit/9c837e4b1eb5eaf9b9c4a373ff5f9de1dfc4d63d.

**Comment by mtrojnar** [comment]
BTW: Also see https://github.com/OpenSC/libp11/commit/887f35a8bd69c3582bee6e06f929c404ac2ef3d3 for the rationale to `pReserved` set in the first place.

OOT: The rationale for validating `pReserved` in SoftHSMv2 (https://github.com/opendnssec/SoftHSMv2/commit/9ddc79915558f3a79ff59079b909fa1c0a280826) is however beyond my comprehension.  What were the expected benefits of adding this check, besides possibly breaking compatibility with future versions PKCS#11?
