### ISSUE TITLE
Using libpkcs11.so as engine with module libsofthsm2.so

### ISSUE THREAD

**Issue by Ovomaltine85** [OpenSC/libp11#96]
Hi,

I'm using softhsm2 as HSM and try to use in conjunction with openssl by engine_pkcs11.so. Everything went fine with RSA keys, but when I try to select ECC keys I got the error that the keys could not be found.
I found out, that the old engine_pkcs11.so can only handle RSA keys, so I tried so migrate to libp11 as it has been merged with engine_pkcs11.

I downloaded libp11-0.4.0, compiled and built it. In OpenSSL (1.0.1t) I tried to load the libpkcs11.so plugin in the following way:
`OpenSSL> engine -t dynamic -pre SO_PATH:/usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libpkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/usr/local/lib/softhsm/libsofthsm2.so`

But I always get the error, that the plugin cannot be loaded:
139730761131664:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(/usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libpkcs11.so): /usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libpkcs11.so: undefined symbol: PKCS11_enumerate_public_keys
139730761131664:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:232:
139730761131664:error:260B6084:engine routines:DYNAMIC_LOAD:dso not found:eng_dyn.c:465:
[Failure]: MODULE_PATH:/usr/local/lib/softhsm/libsofthsm2.so
139730761131664:error:260AC089:engine routines:INT_CTRL_HELPER:invalid cmd name:eng_ctrl.c:131:
139730761131664:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:eng_ctrl.c:311:
     [ unavailable ]

If I switch back to /usr/lib/ssl/engine/engine_pkcs11.so as SO_PATH, no error is thrown, but only RSA keys can be used.

Did I forget to add something? Please tell me what is wrong!
Thank you

**Comment by dwmw2** [comment]
That sounds like the new engine is linking against the old version of libp11.so which is found in your /usr/lib, not the new version that you just built.

Note that on a Linux system you shouldn't need any of that setup. The softhsm package should have registered itself automatically with p11-kit:
```
$ rpm -ql softhsm | grep module
/usr/share/p11-kit/modules/softhsm.module
```
... the engine will load `p11-kit-proxy.so` as its default provider module, and all you need is `-engine pkcs11`.

**Comment by dengert** [comment]
Sounds like libpkcs11.so can not find
      libp11.so To test run: 
     
      ldd /usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libpkcs11.so
    
    This will show what libraries are needed. It should show the path to
    libp11.so.*
    If it does not you may need to do one of the following. 
    
    Place libp11.so in a location that is always searched during
    loading. like /usr/local/lib
    Use the LD_LIBRARY_PATH= environment variable to point to the
    directory with libp11.so
    Recompile and add -rpath (or what ever you OS needs)
    
    Also make sure if the location of libpkcs11.so. It may not be under
    the engines directory. 
    
    
        $ ldd /opt/ossl-1.0.1/lib/libpkcs11.so
        linux-vdso.so.1 =>  (0x00007ffebe0d4000)
        libp11.so.2 => /opt/ossl-1.0.1/lib/libp11.so.2
    (0x00007f2f12867000)
        libcrypto.so.1.0.0 => /opt/ossl-1.0.1/lib/libcrypto.so.1.0.0
    (0x00007f2f1247b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
    (0x00007f2f12098000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
    (0x00007f2f11e94000)
        /lib64/ld-linux-x86-64.so.2 (0x0000563505282000)
    
    
    
    On 8/25/2016 12:45 PM, Ovomaltine85
      wrote:
    
    
      Hi,
      I'm using softhsm2 as HSM and try to use in conjunction with
        openssl by engine_pkcs11.so. Everything went fine with RSA keys,
        but when I try to select ECC keys I got the error that the keys
        could not be found.
        I found out, that the old engine_pkcs11.so can only handle RSA
        keys, so I tried so migrate to libp11 as it has been merged with
        engine_pkcs11.
      I downloaded libp11-0.4.0, compiled and built it. In OpenSSL
        (1.0.1t) I tried to load the libpkcs11.so plugin in the
        following way:
        OpenSSL> engine -t dynamic -pre
          SO_PATH:/usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libpkcs11.so
          -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre
          MODULE_PATH:/usr/local/lib/softhsm/libsofthsm2.so
      But I always get the error, that the plugin cannot be loaded:
        139730761131664:error:25066067:DSO support
        routines:DLFCN_LOAD:could not load the shared
library:dso_dlfcn.c:187:filename(/usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libpkcs11.so):
        /usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libpkcs11.so:
        undefined symbol: PKCS11_enumerate_public_keys
        139730761131664:error:25070067:DSO support
        routines:DSO_load:could not load the shared
        library:dso_lib.c:232:
        139730761131664:error:260B6084:engine routines:DYNAMIC_LOAD:dso
        not found:eng_dyn.c:465:
      139730761131664:error:260AC089:engine
        routines:INT_CTRL_HELPER:invalid cmd name:eng_ctrl.c:131:
        139730761131664:error:260AB089:engine
        routines:ENGINE_ctrl_cmd_string:invalid cmd name:eng_ctrl.c:311:
        [ unavailable ]
      If I switch back to /usr/lib/ssl/engine/engine_pkcs11.so as
        SO_PATH, no error is thrown, but only RSA keys can be used.
      Did I forget to add something? Please tell me what is wrong!
        Thank you
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenSC/libp11","title":"OpenSC/libp11","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenSC/libp11"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Using libpkcs11.so as engine with module libsofthsm2.so (#96)"}],"action":{"name":"View Issue","url":"https://github.com/OpenSC/libp11/issues/96"}}}
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by Ovomaltine85** [comment]
Hi!
Thank you for your replies. I found the mistake!
Everythin was correct, but the only thing I forgot was to execute `ldconfig` after all!

Only a little thing missing, but that took me hours ;-)

Thank you! Discussion can be closed

**Comment by dwmw2** [comment]
@dengert note the the engine bloody well *should* be in the right engines directory.
cf. https://github.com/openssl/openssl/pull/1501

**Comment by Ovomaltine85** [comment]
@dwmw2 what do you mean with direct use by RFC7512 URI?

**Comment by dwmw2** [comment]
@Ovomaltine85 : mean without all the other setup nonsense. Just a simple
 `openssl -engine pkcs11 -keyform engine -key 'pkcs11:token=SoftHSM%20v2;object=bar' …`

**Comment by Ovomaltine85** [comment]
@dwmw2 to be honest, I didn't have a look at RFC7512 at all :-) But this seems to be a promising approach. I will check it out. For that I have to find out how softhsm2 can be addressed by URI.

**Comment by dwmw2** [comment]
The URI is just a standard format for the key identifier string, where the engine used to have its own special non-standard `slot_xxxx-key_yyy` format, and other things like pkcs11-helper used to have their own *different* identifier format. It's handled entirely by the engine, and not at all specific to the token you're using. So yes, SoftHSM2 *can* be addressed by URI. If you change *none* of your other setup that you showed above, and just use a PKCS#11 URI to refer to the object that you want to use, that should work.

That's actually orthogonal to the other part of the puzzle, which is making sure that the right providers are loaded by default and you don't need all that horrid manual setup....

Firstly we added a 'default PKCS#11 provider' to the engine. So you no longer need to manually configure the provider before you even load the engine. You no longer have to do that complex dance with the 'dynamic' engine, and all the `-pre` stuff doing all the setup to load ENGINE_pkcs11. We can just put our engine in the right place, so it gets loaded properly with `ENGINE_by_id("pkcs11")` or `-engine pkcs11`.

So you could configure libp11 with `--with-pkcs11-module=/your/libsofthsmv2.so`. But don't, because we made that part better too...

We actually use `p11-kit-proxy.so` as our default module. P11-kit has a system-wide configuration for which PKCS#11 providers to make available. If you look at the Fedora package of softhsm, for example, you'll see that it includes `/usr/share/p11-kit/modules/softhsm.module`. Likewise the OpenSC package includes a similar file, and the GNOME Keyring package, etc.

Whenever you install a PKCS#11 provider, it should automatically install its p11-kit module file so that it gets *used*. (If you ever find PKCS#11 providers packaged for any distribution which *don't* do this, please file bugs.)

What `p11-kit-proxy.so` does, as its name implies, is load all the configured modules and *proxy* them, making their slots available as slots of itself. So they're all there, automatically, without the user having to do anything special...

```
$  pkcs11-tool --module /usr/lib64/p11-kit-proxy.so --list-slots | grep ^Slot
Slot 0 (0x10): /etc/pki/ca-trust/source
Slot 1 (0x11): /usr/share/pki/ca-trust-source
Slot 2 (0x12): SSH Keys
Slot 3 (0x13): Secret Store
Slot 4 (0x14): Gnome2 Key Storage
Slot 5 (0x15): User Key Storage
Slot 6 (0x16): Virtual hotplug slot
Slot 7 (0x17): SoftHSM slot 0
Slot 8 (0x18): SoftHSM slot 1
Slot 9 (0x19): SoftHSM slot 2
```

That's the tool you might be more familiar with, but perhaps it's more useful to use the GnuTLS `p11tool` to list them, since it shows the URIs for the tokens...
```
$ p11tool --list-all
warning: no token URL was provided for this operation; the available tokens are:

pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=Default%20Trust
pkcs11:model=1.0;manufacturer=Gnome%20Keyring;serial=1%3aSSH%3aHOME;token=SSH%20Keys
pkcs11:model=1.0;manufacturer=Gnome%20Keyring;serial=1%3aSECRET%3aMAIN;token=Secret%20Store
pkcs11:model=1.0;manufacturer=Gnome%20Keyring;serial=1%3aUSER%3aDEFAULT;token=Gnome2%20Key%20Storage
pkcs11:model=1.0;manufacturer=Gnome%20Keyring;serial=1%3aXDG%3aDEFAULT;token=User%20Key%20Storage
pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=108421384210c3f5;token=PIV_II%20%28PIV%20Card%20Holder%20pin%29
pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=5a182c7d75a638ba;token=bar
pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=0a2ed78768b02885;token=foo
```

And that was the final piece of the puzzle. When the distribution has everything set up right, all this stuff should Just Work™. You just install the package of the PKCS#11 provider module you need (SoftHSM, OpenSC, etc.), and it is automatically visible to software.

Any application which can take certificate filenames on the command line or from a config file *should* also accept a PKCS#11 URI, and be able to find objects in any provider which is known to p11-kit. This is already a part of the Fedora packaging guidelines, and other distributions will hopefully catch up eventually.

It means that users can just do stuff like
```
 # dnf install opensc
 # openconnect --certificate='pkcs11:manufacturer=piv_II;id=%01' vpn.example.com
```
... and things Just Work.

**Comment by Ovomaltine85** [comment]
Thank you very much for this great explanation. I gonna check it out!
